# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_wordlist_tsne_highlight.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(679, 622)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tsne_target_word = QtWidgets.QLineEdit(Dialog)
        self.tsne_target_word.setObjectName("tsne_target_word")
        self.verticalLayout.addWidget(self.tsne_target_word)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.Highlight_word1 = QtWidgets.QLineEdit(Dialog)
        self.Highlight_word1.setObjectName("Highlight_word1")
        self.verticalLayout.addWidget(self.Highlight_word1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.Highlight_word2 = QtWidgets.QLineEdit(Dialog)
        self.Highlight_word2.setObjectName("Highlight_word2")
        self.verticalLayout.addWidget(self.Highlight_word2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.Highlight_word3 = QtWidgets.QLineEdit(Dialog)
        self.Highlight_word3.setObjectName("Highlight_word3")
        self.verticalLayout.addWidget(self.Highlight_word3)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.Highlight_word4 = QtWidgets.QLineEdit(Dialog)
        self.Highlight_word4.setObjectName("Highlight_word4")
        self.verticalLayout.addWidget(self.Highlight_word4)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.Highlight_word5 = QtWidgets.QLineEdit(Dialog)
        self.Highlight_word5.setObjectName("Highlight_word5")
        self.verticalLayout.addWidget(self.Highlight_word5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.setWindowIcon(QtGui.QIcon("test.ico"))
        self.label.setText(_translate("Dialog", "Target word "))
        self.tsne_target_word.setText(_translate("Dialog", "additive"))
        self.label_2.setText(_translate("Dialog", "Highlight_word1"))
        self.Highlight_word1.setText(_translate("Dialog", "chloride"))
        self.label_3.setText(_translate("Dialog", "Highlight_word2"))
        self.Highlight_word2.setText(_translate("Dialog", "water"))
        self.label_4.setText(_translate("Dialog", "Highlight_word3"))
        self.Highlight_word3.setText(_translate("Dialog", "acetate"))
        self.label_5.setText(_translate("Dialog", "Highlight_word4"))
        self.Highlight_word4.setText(_translate("Dialog", "ZnO"))
        self.label_6.setText(_translate("Dialog", "Highlight_word5"))
        self.Highlight_word5.setText(_translate("Dialog", "TiO2"))
