# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
items_list = ["连续型", "二分类"]
items_list_1=["Xgboost", "Random Forest","Bagging","AdaBoost","Gradient Boosting","Extra Tree"
    ,"Svm","Decision Tree","Linear Regression","Ridge","MLP"]
items_list_2=["Random Forest","Extra Tree","Gaussian Process","* KNeighbors","Decision Tree","SVM"]

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601,265)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 80, 240, 33))
        self.comboBox.addItem("Regression")                                    # addItem一个一个加
        self.comboBox.addItem("Classification")
        self.comboBox.activated.connect(lambda: self.to_comboBox_2(self.comboBox.currentText()))
        self.comboBox.setObjectName("comboBox")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 80, 291, 33))
        self.comboBox_2.addItems(items_list_1)                             # addItems加一串
        self.comboBox_2.setObjectName("comboBox_2")


        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 171, 341, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")


        self.retranslateUi(Dialog)
        #self.buttonBox.accepted.connect(Dialog.accept)
        #self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Algorithms"))


    def to_comboBox_2(self, text):
        self.comboBox_2.clear()
        if text=="Regression":
            for i in range(len(items_list_1)):
                self.comboBox_2.addItem(items_list_1[i])
        else:
            for i in range(len(items_list_2)):
                self.comboBox_2.addItem(items_list_2[i])



