import sys
import os
from pymatgen.io.cif import CifParser
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QFileDialog, QTextEdit, QMessageBox, QLabel
from collections import Counter
from mendeleev import element
import csv

class FileSelectionWidget(QWidget):
    def __init__(self):
        super().__init__()

        self.initUI()

    def initUI(self):
        layout = QVBoxLayout()

        self.setWindowTitle("请选择CIF文件夹")
        self.setGeometry(100, 100, 600, 200)

        self.folder_path_label = QLabel("CIF文件夹路径:")
        layout.addWidget(self.folder_path_label)

        self.folder_path_text = QTextEdit()
        self.folder_path_text.setFixedHeight(30)
        layout.addWidget(self.folder_path_text)

        self.folder_button = QPushButton("浏览文件夹")
        self.folder_button.clicked.connect(self.folderDialog)
        layout.addWidget(self.folder_button)

        self.save_path_label = QLabel("保存路径:")
        layout.addWidget(self.save_path_label)

        self.save_path_button = QPushButton("选择保存路径")
        self.save_path_button.clicked.connect(self.selectSavePath)
        layout.addWidget(self.save_path_button)

        self.save_path_text = QTextEdit()
        self.save_path_text.setFixedHeight(30)
        layout.addWidget(self.save_path_text)

        self.confirm_button = QPushButton("确认")
        self.confirm_button.clicked.connect(self.executeCode)
        layout.addWidget(self.confirm_button)

        self.setLayout(layout)

    def folderDialog(self):
        folderPath = QFileDialog.getExistingDirectory(self, '选择文件夹')
        if folderPath:
            self.folder_path = folderPath
            self.folder_path_text.setText(self.folder_path)

    def selectSavePath(self):
        savePath, _ = QFileDialog.getSaveFileName(self, '选择保存路径', '', 'CSV Files (*.csv)')
        if savePath:
            self.save_path = savePath
            self.save_path_text.setText(self.save_path)

    def executeCode(self):
        if hasattr(self, 'folder_path') and hasattr(self, 'save_path'):
            print("正在处理，请稍候.....")



            fieldnames =['element1_x', 'element1_y', 'element1_z', 'element2_x', 'element2_y', 'element2_z', 'element3_x',
             'element3_y', 'element3_z', 'element4_x', 'element4_y', 'element4_z', 'element5_x', 'element5_y',
             'element5_z', 'element1_abundance_crust', 'element1_abundance_sea', 'element1_annotation',
             'element1_atomic_number', 'element1_atomic_radius', 'element1_atomic_radius_rahm',
             'element1_atomic_volume', 'element1_atomic_weight', 'element1_atomic_weight_uncertainty', 'element1_block',
             'element1_c6', 'element1_c6_gb', 'element1_cas', 'element1_covalent_radius_bragg',
             'element1_covalent_radius_cordero', 'element1_covalent_radius_pyykko',
             'element1_covalent_radius_pyykko_double', 'element1_covalent_radius_pyykko_triple', 'element1_cpk_color',
             'element1_density',
             'element1_description', 'element1_dipole_polarizability', 'element1_dipole_polarizability_unc',
             'element1_discoverers', 'element1_discovery_location', 'element1_discovery_year', 'element1_ec',
             'element1_econf', 'element1_electron_affinity', 'element1_en_allen', 'element1_en_ghosh',
             'element1_en_pauling', 'element1_evaporation_heat', 'element1_fusion_heat', 'element1_gas_basicity',
             'element1_geochemical_class', 'element1_glawe_number', 'element1_goldschmidt_class', 'element1_group',
             'element1_group_id', 'element1_heat_of_formation',
             'element1_is_monoisotopic', 'element1_is_radioactive', 'element1_isotopes', 'element1_jmol_color',
             'element1_lattice_constant', 'element1_lattice_structure', 'element1_mendeleev_number',
             'element1_metallic_radius', 'element1_metallic_radius_c12',
             'element1_molar_heat_capacity', 'element1_molcas_gv_color', 'element1_name', 'element1_name_origin',
             'element1_period', 'element1_pettifor_number', 'element1_phase_transitions', 'element1_proton_affinity',
             'element1_screening_constants', 'element1_sources',
             'element1_specific_heat_capacity', 'element1_symbol', 'element1_thermal_conductivity', 'element1_uses',
             'element1_vdw_radius', 'element1_vdw_radius_alvarez', 'element1_vdw_radius_batsanov',
             'element1_vdw_radius_bondi', 'element1_vdw_radius_dreiding',
             'element1_vdw_radius_mm3', 'element1_vdw_radius_rt', 'element1_vdw_radius_truhlar',
             'element1_vdw_radius_uff', 'element2_abundance_crust', 'element2_abundance_sea', 'element2_annotation',
             'element2_atomic_number', 'element2_atomic_radius', 'element2_atomic_radius_rahm',
             'element2_atomic_volume', 'element2_atomic_weight', 'element2_atomic_weight_uncertainty', 'element2_block',
             'element2_c6', 'element2_c6_gb', 'element2_cas', 'element2_covalent_radius_bragg',
             'element2_covalent_radius_cordero', 'element2_covalent_radius_pyykko',
             'element2_covalent_radius_pyykko_double', 'element2_covalent_radius_pyykko_triple', 'element2_cpk_color',
             'element2_density',
             'element2_description', 'element2_dipole_polarizability', 'element2_dipole_polarizability_unc',
             'element2_discoverers', 'element2_discovery_location', 'element2_discovery_year', 'element2_ec',
             'element2_econf', 'element2_electron_affinity', 'element2_en_allen', 'element2_en_ghosh',
             'element2_en_pauling', 'element2_evaporation_heat', 'element2_fusion_heat', 'element2_gas_basicity',
             'element2_geochemical_class', 'element2_glawe_number', 'element2_goldschmidt_class', 'element2_group',
             'element2_group_id', 'element2_heat_of_formation',
             'element2_is_monoisotopic', 'element2_is_radioactive', 'element2_isotopes', 'element2_jmol_color',
             'element2_lattice_constant', 'element2_lattice_structure', 'element2_mendeleev_number',
             'element2_metallic_radius', 'element2_metallic_radius_c12',
             'element2_molar_heat_capacity', 'element2_molcas_gv_color', 'element2_name', 'element2_name_origin',
             'element2_period', 'element2_pettifor_number', 'element2_phase_transitions', 'element2_proton_affinity',
             'element2_screening_constants', 'element2_sources',
             'element2_specific_heat_capacity', 'element2_symbol', 'element2_thermal_conductivity', 'element2_uses',
             'element2_vdw_radius', 'element2_vdw_radius_alvarez', 'element2_vdw_radius_batsanov',
             'element2_vdw_radius_bondi', 'element2_vdw_radius_dreiding',
             'element2_vdw_radius_mm3', 'element2_vdw_radius_rt', 'element2_vdw_radius_truhlar',
             'element2_vdw_radius_uff', 'element3_abundance_crust', 'element3_abundance_sea', 'element3_annotation',
             'element3_atomic_number', 'element3_atomic_radius', 'element3_atomic_radius_rahm',
             'element3_atomic_volume', 'element3_atomic_weight', 'element3_atomic_weight_uncertainty', 'element3_block',
             'element3_c6', 'element3_c6_gb', 'element3_cas', 'element3_covalent_radius_bragg',
             'element3_covalent_radius_cordero', 'element3_covalent_radius_pyykko',
             'element3_covalent_radius_pyykko_double', 'element3_covalent_radius_pyykko_triple', 'element3_cpk_color',
             'element3_density',
             'element3_description', 'element3_dipole_polarizability', 'element3_dipole_polarizability_unc',
             'element3_discoverers', 'element3_discovery_location', 'element3_discovery_year', 'element3_ec',
             'element3_econf', 'element3_electron_affinity', 'element3_en_allen', 'element3_en_ghosh',
             'element3_en_pauling', 'element3_evaporation_heat', 'element3_fusion_heat', 'element3_gas_basicity',
             'element3_geochemical_class', 'element3_glawe_number', 'element3_goldschmidt_class', 'element3_group',
             'element3_group_id', 'element3_heat_of_formation',
             'element3_is_monoisotopic', 'element3_is_radioactive', 'element3_isotopes', 'element3_jmol_color',
             'element3_lattice_constant', 'element3_lattice_structure', 'element3_mendeleev_number',
             'element3_metallic_radius', 'element3_metallic_radius_c12',
             'element3_molar_heat_capacity', 'element3_molcas_gv_color', 'element3_name', 'element3_name_origin',
             'element3_period', 'element3_pettifor_number', 'element3_phase_transitions', 'element3_proton_affinity',
             'element3_screening_constants', 'element3_sources',
             'element3_specific_heat_capacity', 'element3_symbol', 'element3_thermal_conductivity', 'element3_uses',
             'element3_vdw_radius', 'element3_vdw_radius_alvarez', 'element3_vdw_radius_batsanov',
             'element3_vdw_radius_bondi', 'element3_vdw_radius_dreiding',
             'element3_vdw_radius_mm3', 'element3_vdw_radius_rt', 'element3_vdw_radius_truhlar',
             'element3_vdw_radius_uff', 'element4_abundance_crust', 'element4_abundance_sea', 'element4_annotation',
             'element4_atomic_number', 'element4_atomic_radius', 'element4_atomic_radius_rahm',
             'element4_atomic_volume', 'element4_atomic_weight', 'element4_atomic_weight_uncertainty', 'element4_block',
             'element4_c6', 'element4_c6_gb', 'element4_cas', 'element4_covalent_radius_bragg',
             'element4_covalent_radius_cordero', 'element4_covalent_radius_pyykko',
             'element4_covalent_radius_pyykko_double', 'element4_covalent_radius_pyykko_triple', 'element4_cpk_color',
             'element4_density',
             'element4_description', 'element4_dipole_polarizability', 'element4_dipole_polarizability_unc',
             'element4_discoverers', 'element4_discovery_location', 'element4_discovery_year', 'element4_ec',
             'element4_econf', 'element4_electron_affinity', 'element4_en_allen', 'element4_en_ghosh',
             'element4_en_pauling', 'element4_evaporation_heat', 'element4_fusion_heat', 'element4_gas_basicity',
             'element4_geochemical_class', 'element4_glawe_number', 'element4_goldschmidt_class', 'element4_group',
             'element4_group_id', 'element4_heat_of_formation',
             'element4_is_monoisotopic', 'element4_is_radioactive', 'element4_isotopes', 'element4_jmol_color',
             'element4_lattice_constant', 'element4_lattice_structure', 'element4_mendeleev_number',
             'element4_metallic_radius', 'element4_metallic_radius_c12',
             'element4_molar_heat_capacity', 'element4_molcas_gv_color', 'element4_name', 'element4_name_origin',
             'element4_period', 'element4_pettifor_number', 'element4_phase_transitions', 'element4_proton_affinity',
             'element4_screening_constants', 'element4_sources',
             'element4_specific_heat_capacity', 'element4_symbol', 'element4_thermal_conductivity', 'element4_uses',
             'element4_vdw_radius', 'element4_vdw_radius_alvarez', 'element4_vdw_radius_batsanov',
             'element4_vdw_radius_bondi', 'element4_vdw_radius_dreiding',
             'element4_vdw_radius_mm3', 'element4_vdw_radius_rt', 'element4_vdw_radius_truhlar',
             'element4_vdw_radius_uff', 'element5_abundance_crust', 'element5_abundance_sea', 'element5_annotation',
             'element5_atomic_number', 'element5_atomic_radius', 'element5_atomic_radius_rahm',
             'element5_atomic_volume', 'element5_atomic_weight', 'element5_atomic_weight_uncertainty', 'element5_block',
             'element5_c6', 'element5_c6_gb', 'element5_cas', 'element5_covalent_radius_bragg',
             'element5_covalent_radius_cordero', 'element5_covalent_radius_pyykko',
             'element5_covalent_radius_pyykko_double', 'element5_covalent_radius_pyykko_triple', 'element5_cpk_color',
             'element5_density',
             'element5_description', 'element5_dipole_polarizability', 'element5_dipole_polarizability_unc',
             'element5_discoverers', 'element5_discovery_location', 'element5_discovery_year', 'element5_ec',
             'element5_econf', 'element5_electron_affinity', 'element5_en_allen', 'element5_en_ghosh',
             'element5_en_pauling', 'element5_evaporation_heat', 'element5_fusion_heat', 'element5_gas_basicity',
             'element5_geochemical_class', 'element5_glawe_number', 'element5_goldschmidt_class', 'element5_group',
             'element5_group_id', 'element5_heat_of_formation','element5_is_monoisotopic', 'element5_is_radioactive', 'element5_isotopes', 'element5_jmol_color',
             'element5_lattice_constant', 'element5_lattice_structure', 'element5_mendeleev_number',
             'element5_metallic_radius', 'element5_metallic_radius_c12',
             'element5_molar_heat_capacity', 'element5_molcas_gv_color', 'element5_name', 'element5_name_origin',
             'element5_period', 'element5_pettifor_number', 'element5_phase_transitions', 'element5_proton_affinity',
             'element5_screening_constants', 'element5_sources',
             'element5_specific_heat_capacity', 'element5_symbol', 'element5_thermal_conductivity', 'element5_uses',
             'element5_vdw_radius', 'element5_vdw_radius_alvarez', 'element5_vdw_radius_batsanov',
             'element5_vdw_radius_bondi', 'element5_vdw_radius_dreiding',
             'element5_vdw_radius_mm3', 'element5_vdw_radius_rt', 'element5_vdw_radius_truhlar',
             'element5_vdw_radius_uff', 'unit_cell_length_x', 'unit_cell_length_y', 'unit_cell_length_z']

            with open(self.save_path, mode='a+', newline='',encoding='utf-8') as file:
                writer = csv.DictWriter(file, fieldnames=fieldnames)
                writer.writeheader()

                for filename in os.listdir(self.folder_path):
                    if filename.endswith(".cif"):
                        cif_parser = CifParser(f'{self.folder_path}/'+ filename)
                        structure = cif_parser.get_structures()[0]
                        species = structure.species
                        lattice = structure.lattice
                        symbol_list = [element_.symbol for element_ in species]

                        element1 = element(symbol_list[0])
                        element2 = element(symbol_list[1])
                        element3 = element(symbol_list[2])
                        element4 = element(symbol_list[3])
                        element5 = element(symbol_list[4])

                        writer.writerow({
                            'element1_x': structure.cart_coords[0][0],
        'element1_y': structure.cart_coords[0][1],
        'element1_z': structure.cart_coords[0][2],
        'element2_x': structure.cart_coords[1][0],
        'element2_y': structure.cart_coords[1][1],
        'element2_z': structure.cart_coords[1][2],
        'element3_x': structure.cart_coords[2][0],
        'element3_y': structure.cart_coords[2][1],
        'element3_z': structure.cart_coords[2][2],
        'element4_x': structure.cart_coords[3][0],
        'element4_y': structure.cart_coords[3][1],
        'element4_z': structure.cart_coords[3][2],
        'element5_x': structure.cart_coords[4][0],
        'element5_y': structure.cart_coords[4][1],
        'element5_z': structure.cart_coords[4][2],
        'element1_abundance_crust': element1.abundance_crust,
        'element1_abundance_sea': element1.abundance_sea,
        'element1_annotation': element1.annotation,
        'element1_atomic_number': element1.atomic_number,
        'element1_atomic_radius': element1.atomic_radius,
        'element1_atomic_radius_rahm': element1.atomic_radius_rahm,
        'element1_atomic_volume': element1.atomic_volume,
        'element1_atomic_weight': element1.atomic_weight,
        'element1_atomic_weight_uncertainty': element1.atomic_weight_uncertainty,
        'element1_block': element1.block,
        'element1_c6': element1.c6,
        'element1_c6_gb': element1.c6_gb,
        'element1_cas': element1.cas,
        'element1_covalent_radius_bragg': element1.covalent_radius_bragg,
        'element1_covalent_radius_cordero': element1.covalent_radius_cordero,
        'element1_covalent_radius_pyykko': element1.covalent_radius_pyykko,
        'element1_covalent_radius_pyykko_double': element1.covalent_radius_pyykko_double,
        'element1_covalent_radius_pyykko_triple': element1.covalent_radius_pyykko_triple,
        'element1_cpk_color': element1.cpk_color,
        'element1_density': element1.density,
        'element1_description': element1.description,
        'element1_dipole_polarizability': element1.dipole_polarizability,
        'element1_dipole_polarizability_unc': element1.dipole_polarizability_unc,
        'element1_discoverers': element1.discoverers,
        'element1_discovery_location': element1.discovery_location,
        'element1_discovery_year': element1.discovery_year,
        'element1_ec': element1.ec,
        'element1_econf': element1.econf,
        'element1_electron_affinity': element1.electron_affinity,
        'element1_en_allen': element1.en_allen,
        'element1_en_ghosh': element1.en_ghosh,
        'element1_en_pauling': element1.en_pauling,
        'element1_evaporation_heat': element1.evaporation_heat,
        'element1_fusion_heat': element1.fusion_heat,
        'element1_gas_basicity': element1.gas_basicity,
        'element1_geochemical_class': element1.geochemical_class,
        'element1_glawe_number': element1.glawe_number,
        'element1_goldschmidt_class': element1.goldschmidt_class,
        'element1_group': element1.group,
        'element1_group_id': element1.group_id,
        'element1_heat_of_formation': element1.heat_of_formation,
        'element1_is_monoisotopic': element1.is_monoisotopic,
        'element1_is_radioactive': element1.is_radioactive,
        'element1_isotopes': element1.isotopes,
        'element1_jmol_color': element1.jmol_color,
        'element1_lattice_constant': element1.lattice_constant,
        'element1_lattice_structure': element1.lattice_structure,
        'element1_mendeleev_number': element1.mendeleev_number,
        'element1_metallic_radius': element1.metallic_radius,
        'element1_metallic_radius_c12': element1.metallic_radius_c12,
        'element1_molar_heat_capacity': element1.molar_heat_capacity,
        'element1_molcas_gv_color': element1.molcas_gv_color,
        'element1_name': element1.name,
        'element1_name_origin': element1.name_origin,
        'element1_period': element1.period,
        'element1_pettifor_number': element1.pettifor_number,
        'element1_phase_transitions': element1.phase_transitions,
        'element1_proton_affinity': element1.proton_affinity,
        'element1_screening_constants': element1.screening_constants,
        'element1_sources': element1.sources,
        'element1_specific_heat_capacity': element1.specific_heat_capacity,
        'element1_symbol': element1.symbol,
        'element1_thermal_conductivity': element1.thermal_conductivity,
        'element1_uses': element1.uses,
        'element1_vdw_radius': element1.vdw_radius,
        'element1_vdw_radius_alvarez': element1.vdw_radius_alvarez,
        'element1_vdw_radius_batsanov': element1.vdw_radius_batsanov,
        'element1_vdw_radius_bondi': element1.vdw_radius_bondi,
        'element1_vdw_radius_dreiding': element1.vdw_radius_dreiding,
        'element1_vdw_radius_mm3': element1.vdw_radius_mm3,
        'element1_vdw_radius_rt': element1.vdw_radius_rt,
        'element1_vdw_radius_truhlar': element1.vdw_radius_truhlar,
        'element1_vdw_radius_uff': element1.vdw_radius_uff,
        'element2_abundance_crust': element2.abundance_crust,
        'element2_abundance_sea': element2.abundance_sea,
        'element2_annotation': element2.annotation,
        'element2_atomic_number': element2.atomic_number,
        'element2_atomic_radius': element2.atomic_radius,
        'element2_atomic_radius_rahm': element2.atomic_radius_rahm,
        'element2_atomic_volume': element2.atomic_volume,
        'element2_atomic_weight': element2.atomic_weight,
        'element2_atomic_weight_uncertainty': element2.atomic_weight_uncertainty,
        'element2_block': element2.block,
        'element2_c6': element2.c6,
        'element2_c6_gb': element2.c6_gb,
        'element2_cas': element2.cas,
        'element2_covalent_radius_bragg': element2.covalent_radius_bragg,
        'element2_covalent_radius_cordero': element2.covalent_radius_cordero,
        'element2_covalent_radius_pyykko': element2.covalent_radius_pyykko,
        'element2_covalent_radius_pyykko_double': element2.covalent_radius_pyykko_double,
        'element2_covalent_radius_pyykko_triple': element2.covalent_radius_pyykko_triple,
        'element2_cpk_color': element2.cpk_color,
        'element2_density': element2.density,
        'element2_description': element2.description,
        'element2_dipole_polarizability': element2.dipole_polarizability,
        'element2_dipole_polarizability_unc': element2.dipole_polarizability_unc,
        'element2_discoverers': element2.discoverers,
        'element2_discovery_location': element2.discovery_location,
        'element2_discovery_year': element2.discovery_year,
        'element2_ec': element2.ec,
        'element2_econf': element2.econf,
        'element2_electron_affinity': element2.electron_affinity,
        'element2_en_allen': element2.en_allen,
        'element2_en_ghosh': element2.en_ghosh,
        'element2_en_pauling': element2.en_pauling,
        'element2_evaporation_heat': element2.evaporation_heat,
        'element2_fusion_heat': element2.fusion_heat,
        'element2_gas_basicity': element2.gas_basicity,
        'element2_geochemical_class': element2.geochemical_class,
        'element2_glawe_number': element2.glawe_number,
        'element2_goldschmidt_class': element2.goldschmidt_class,
        'element2_group': element2.group,
        'element2_group_id': element2.group_id,
        'element2_heat_of_formation': element2.heat_of_formation,
        'element2_is_monoisotopic': element2.is_monoisotopic,
        'element2_is_radioactive': element2.is_radioactive,
        'element2_isotopes': element2.isotopes,
        'element2_jmol_color': element2.jmol_color,
        'element2_lattice_constant': element2.lattice_constant,
        'element2_lattice_structure': element2.lattice_structure,
        'element2_mendeleev_number': element2.mendeleev_number,
        'element2_metallic_radius': element2.metallic_radius,
        'element2_metallic_radius_c12': element2.metallic_radius_c12,
        'element2_molar_heat_capacity': element2.molar_heat_capacity,
        'element2_molcas_gv_color': element2.molcas_gv_color,
        'element2_name': element2.name,
        'element2_name_origin': element2.name_origin,
        'element2_period': element2.period,
        'element2_pettifor_number': element2.pettifor_number,
        'element2_phase_transitions': element2.phase_transitions,
        'element2_proton_affinity': element2.proton_affinity,
        'element2_screening_constants': element2.screening_constants,
        'element2_sources': element2.sources,
        'element2_specific_heat_capacity': element2.specific_heat_capacity,
        'element2_symbol': element2.symbol,
        'element2_thermal_conductivity': element2.thermal_conductivity,
        'element2_uses': element2.uses,
        'element2_vdw_radius': element2.vdw_radius,
        'element2_vdw_radius_alvarez': element2.vdw_radius_alvarez,
        'element2_vdw_radius_batsanov': element2.vdw_radius_batsanov,
        'element2_vdw_radius_bondi': element2.vdw_radius_bondi,
        'element2_vdw_radius_dreiding': element2.vdw_radius_dreiding,
        'element2_vdw_radius_mm3': element2.vdw_radius_mm3,
        'element2_vdw_radius_rt': element2.vdw_radius_rt,
        'element2_vdw_radius_truhlar': element2.vdw_radius_truhlar,
        'element2_vdw_radius_uff': element2.vdw_radius_uff,
        'element3_abundance_crust': element3.abundance_crust,
        'element3_abundance_sea': element3.abundance_sea,
        'element3_annotation': element3.annotation,
        'element3_atomic_number': element3.atomic_number,
        'element3_atomic_radius': element3.atomic_radius,
        'element3_atomic_radius_rahm': element3.atomic_radius_rahm,
        'element3_atomic_volume': element3.atomic_volume,
        'element3_atomic_weight': element3.atomic_weight,
        'element3_atomic_weight_uncertainty': element3.atomic_weight_uncertainty,
        'element3_block': element3.block,
        'element3_c6': element3.c6,
        'element3_c6_gb': element3.c6_gb,
        'element3_cas': element3.cas,
        'element3_covalent_radius_bragg': element3.covalent_radius_bragg,
        'element3_covalent_radius_cordero': element3.covalent_radius_cordero,
        'element3_covalent_radius_pyykko': element3.covalent_radius_pyykko,
        'element3_covalent_radius_pyykko_double': element3.covalent_radius_pyykko_double,
        'element3_covalent_radius_pyykko_triple': element3.covalent_radius_pyykko_triple,
        'element3_cpk_color': element3.cpk_color,
        'element3_density': element3.density,
        'element3_description': element3.description,
        'element3_dipole_polarizability': element3.dipole_polarizability,
        'element3_dipole_polarizability_unc': element3.dipole_polarizability_unc,
        'element3_discoverers': element3.discoverers,
        'element3_discovery_location': element3.discovery_location,
        'element3_discovery_year': element3.discovery_year,
        'element3_ec': element3.ec,
        'element3_econf': element3.econf,
        'element3_electron_affinity': element3.electron_affinity,
        'element3_en_allen': element3.en_allen,
        'element3_en_ghosh': element3.en_ghosh,
        'element3_en_pauling': element3.en_pauling,
        'element3_evaporation_heat': element3.evaporation_heat,
        'element3_fusion_heat': element3.fusion_heat,
        'element3_gas_basicity': element3.gas_basicity,
        'element3_geochemical_class': element3.geochemical_class,
        'element3_glawe_number': element3.glawe_number,
        'element3_goldschmidt_class': element3.goldschmidt_class,
        'element3_group': element3.group,
        'element3_group_id': element3.group_id,
        'element3_heat_of_formation': element3.heat_of_formation,
        'element3_is_monoisotopic': element3.is_monoisotopic,
        'element3_is_radioactive': element3.is_radioactive,
        'element3_isotopes': element3.isotopes,
        'element3_jmol_color': element3.jmol_color,
        'element3_lattice_constant': element3.lattice_constant,
        'element3_lattice_structure': element3.lattice_structure,
        'element3_mendeleev_number': element3.mendeleev_number,
        'element3_metallic_radius': element3.metallic_radius,
        'element3_metallic_radius_c12': element3.metallic_radius_c12,
        'element3_molar_heat_capacity': element3.molar_heat_capacity,
        'element3_molcas_gv_color': element3.molcas_gv_color,
        'element3_name': element3.name,
        'element3_name_origin': element3.name_origin,
        'element3_period': element3.period,
        'element3_pettifor_number': element3.pettifor_number,
        'element3_phase_transitions': element3.phase_transitions,
        'element3_proton_affinity': element3.proton_affinity,
        'element3_screening_constants': element3.screening_constants,
        'element3_sources': element3.sources,
        'element3_specific_heat_capacity': element3.specific_heat_capacity,
        'element3_symbol': element3.symbol,
        'element3_thermal_conductivity': element3.thermal_conductivity,
        'element3_uses': element3.uses,
        'element3_vdw_radius': element3.vdw_radius,
        'element3_vdw_radius_alvarez': element3.vdw_radius_alvarez,
        'element3_vdw_radius_batsanov': element3.vdw_radius_batsanov,
        'element3_vdw_radius_bondi': element3.vdw_radius_bondi,
        'element3_vdw_radius_dreiding': element3.vdw_radius_dreiding,
        'element3_vdw_radius_mm3': element3.vdw_radius_mm3,
        'element3_vdw_radius_rt': element3.vdw_radius_rt,
        'element3_vdw_radius_truhlar': element3.vdw_radius_truhlar,
        'element3_vdw_radius_uff': element3.vdw_radius_uff,
        'element4_abundance_crust': element4.abundance_crust,
        'element4_block': element4.block,
        'element4_c6': element4.c6,
        'element4_c6_gb': element4.c6_gb,
        'element4_cas': element4.cas,
        'element4_covalent_radius_bragg': element4.covalent_radius_bragg,
        'element4_covalent_radius_cordero': element4.covalent_radius_cordero,
        'element4_covalent_radius_pyykko': element4.covalent_radius_pyykko,
        'element4_covalent_radius_pyykko_double': element4.covalent_radius_pyykko_double,
        'element4_covalent_radius_pyykko_triple': element4.covalent_radius_pyykko_triple,
        'element4_cpk_color': element4.cpk_color,
        'element4_density': element4.density,
        'element4_description': element4.description,
        'element4_dipole_polarizability': element4.dipole_polarizability,
        'element4_dipole_polarizability_unc': element4.dipole_polarizability_unc,
        'element4_discoverers': element4.discoverers,
        'element4_discovery_location': element4.discovery_location,
        'element4_discovery_year': element4.discovery_year,
        'element4_ec': element4.ec,
        'element4_econf': element4.econf,
        'element4_electron_affinity': element4.electron_affinity,
        'element4_en_allen': element4.en_allen,
        'element4_en_ghosh': element4.en_ghosh,
        'element4_en_pauling': element4.en_pauling,
        'element4_evaporation_heat': element4.evaporation_heat,
        'element4_fusion_heat': element4.fusion_heat,
        'element4_gas_basicity': element4.gas_basicity,
        'element4_geochemical_class': element4.geochemical_class,
        'element4_glawe_number': element4.glawe_number,
        'element4_goldschmidt_class': element4.goldschmidt_class,
        'element4_group': element4.group,
        'element4_group_id': element4.group_id,
        'element4_heat_of_formation': element4.heat_of_formation,
        'element4_is_monoisotopic': element4.is_monoisotopic,
        'element4_is_radioactive': element4.is_radioactive,
        'element4_isotopes': element4.isotopes,
        'element4_jmol_color': element4.jmol_color,
        'element4_lattice_constant': element4.lattice_constant,
        'element4_lattice_structure': element4.lattice_structure,
        'element4_mendeleev_number': element4.mendeleev_number,
        'element4_metallic_radius': element4.metallic_radius,
        'element4_metallic_radius_c12': element4.metallic_radius_c12,
        'element4_molar_heat_capacity': element4.molar_heat_capacity,
        'element4_molcas_gv_color': element4.molcas_gv_color,
        'element4_name': element4.name,
        'element4_name_origin': element4.name_origin,
        'element4_period': element4.period,
        'element4_pettifor_number': element4.pettifor_number,
        'element4_phase_transitions': element4.phase_transitions,
        'element4_proton_affinity': element4.proton_affinity,
        'element4_screening_constants': element4.screening_constants,
        'element4_sources': element4.sources,
        'element4_specific_heat_capacity': element4.specific_heat_capacity,
        'element4_symbol': element4.symbol,
        'element4_thermal_conductivity': element4.thermal_conductivity,
        'element4_uses': element4.uses,
        'element4_vdw_radius': element4.vdw_radius,
        'element4_vdw_radius_alvarez': element4.vdw_radius_alvarez,
        'element4_vdw_radius_batsanov': element4.vdw_radius_batsanov,
        'element4_vdw_radius_bondi': element4.vdw_radius_bondi,
        'element4_vdw_radius_dreiding': element4.vdw_radius_dreiding,
        'element4_vdw_radius_mm3': element4.vdw_radius_mm3,
        'element4_vdw_radius_rt': element4.vdw_radius_rt,
        'element4_vdw_radius_truhlar': element4.vdw_radius_truhlar,
        'element4_vdw_radius_uff': element4.vdw_radius_uff,
        'element5_abundance_crust': element5.abundance_crust,
        'element5_block': element5.block,
        'element5_c6': element5.c6,
        'element5_c6_gb': element5.c6_gb,
        'element5_cas': element5.cas,
        'element5_covalent_radius_bragg': element5.covalent_radius_bragg,
        'element5_covalent_radius_cordero': element5.covalent_radius_cordero,
        'element5_covalent_radius_pyykko': element5.covalent_radius_pyykko,
        'element5_covalent_radius_pyykko_double': element5.covalent_radius_pyykko_double,
        'element5_covalent_radius_pyykko_triple': element5.covalent_radius_pyykko_triple,
        'element5_cpk_color': element5.cpk_color,
        'element5_density': element5.density,
        'element5_description': element5.description,
        'element5_dipole_polarizability': element5.dipole_polarizability,
        'element5_dipole_polarizability_unc': element5.dipole_polarizability_unc,
        'element5_discoverers': element5.discoverers,
        'element5_discovery_location': element5.discovery_location,
        'element5_discovery_year': element5.discovery_year,
        'element5_ec': element5.ec,
        'element5_econf': element5.econf,
        'element5_electron_affinity': element5.electron_affinity,
        'element5_en_allen': element5.en_allen,
        'element5_en_ghosh': element5.en_ghosh,
        'element5_en_pauling': element5.en_pauling,
        'element5_evaporation_heat': element5.evaporation_heat,
        'element5_fusion_heat': element5.fusion_heat,
        'element5_gas_basicity': element5.gas_basicity,
        'element5_geochemical_class': element5.geochemical_class,
        'element5_glawe_number': element5.glawe_number,
        'element5_goldschmidt_class': element5.goldschmidt_class,
        'element5_group': element5.group,
        'element5_group_id': element5.group_id,
        'element5_heat_of_formation': element5.heat_of_formation,
        'element5_is_monoisotopic': element5.is_monoisotopic,
        'element5_is_radioactive': element5.is_radioactive,
        'element5_isotopes': element5.isotopes,
        'element5_jmol_color': element5.jmol_color,
        'element5_lattice_constant': element5.lattice_constant,
        'element5_lattice_structure': element5.lattice_structure,
        'element5_mendeleev_number': element5.mendeleev_number,
        'element5_metallic_radius': element5.metallic_radius,
        'element5_metallic_radius_c12': element5.metallic_radius_c12,
        'element5_molar_heat_capacity': element5.molar_heat_capacity,
        'element5_molcas_gv_color': element5.molcas_gv_color,
        'element5_name': element5.name,
        'element5_name_origin': element5.name_origin,
        'element5_period': element5.period,
        'element5_pettifor_number': element5.pettifor_number,
        'element5_phase_transitions': element5.phase_transitions,
        'element5_proton_affinity': element5.proton_affinity,
        'element5_screening_constants': element5.screening_constants,
        'element5_sources': element5.sources,
        'element5_specific_heat_capacity': element5.specific_heat_capacity,
        'element5_symbol': element5.symbol,
        'element5_thermal_conductivity': element5.thermal_conductivity,
        'element5_uses': element5.uses,
        'element5_vdw_radius': element5.vdw_radius,
        'element5_vdw_radius_alvarez': element5.vdw_radius_alvarez,
        'element5_vdw_radius_batsanov': element5.vdw_radius_batsanov,
        'element5_vdw_radius_bondi': element5.vdw_radius_bondi,
        'element5_vdw_radius_dreiding': element5.vdw_radius_dreiding,
        'element5_vdw_radius_mm3': element5.vdw_radius_mm3,
        'element5_vdw_radius_rt': element5.vdw_radius_rt,
        'element5_vdw_radius_truhlar': element5.vdw_radius_truhlar,
        'element5_vdw_radius_uff': element5.vdw_radius_uff,
        'unit_cell_length_x':lattice.abc[0],
        'unit_cell_length_y':lattice.abc[1],
        'unit_cell_length_z':lattice.abc[2]
                        })

            QMessageBox.information(self, "提示", "处理完成")
        else:
            QMessageBox.warning(self, "警告", "请先选择文件夹和保存路径")

if __name__ == '__main__':
    app = QApplication(sys.argv)

    window = FileSelectionWidget()
    window.show()

    sys.exit(app.exec_())